<h1>
	<?php echo $this->escapeHtml($this->title); ?> 
	<span class="sub-info"> - <?php echo $this->escapeHtml($this->subtitle); ?></span>
</h1>

<?php

/**
 * @var \Zend\Form\Form
 */
$form = $this->form;

echo $this->partial('_formMessages.phtml', array(
    'success' => $this->success, 
    'error' => $this->error, 
    'info' => $this->info)
);

$this->formElementErrors()
    ->setMessageOpenFormat(
        '<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
    ->setMessageCloseString('</div>')
    ->render($form);

$form->setAttribute('action', 
    $this->url('autor/default', array(
        'controller' => 'autor',
        'action' => 'cadastrar'
    ))
);

$form->prepare();

echo $this->form()->openTag($form);

?>
<div class="zend_form">
	<div class="row">
		<?php foreach ($form as $element): ?>
            <div class="col-xs-12 col-sm-6 col-lg-4">
            	<div class="form-group">
                    <?php
                    if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button)
                    {
                        if (!$element instanceof Zend\Form\Element\Button)
                            echo $this->formLabel($element);
                        echo $this->formElement($element);
                    }
                    else
                        echo $this->formElement($element) . $this->formElementErrors($element);
                    ?>
            	</div>
            </div>
        <?php endforeach; ?>
	</div>
</div>
<?php

echo $this->form()->closeTag($form);

?>