<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap/bootstrap-select.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/i18n/bootstrap-select-pt_BR.min.js'))
            ->prependFile($this->basePath('js/bootstrap/bootstrap-filestyle.min.js'))
            ->prependFile($this->basePath('js/bootstrap/bootstrap-select.min.js'))
            ->prependFile($this->basePath('js/validator.min.js'))
            ->prependFile($this->basePath('js/bootstrap/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->basePath('autor')?>">Autores</a></li>
                        <li>
                        	<a href="javascript:void(0)">Material</a>
                        	<ul class="nav navbar-nav sub-menu">
                        		<li><a href="<?php echo $this->basePath('material/livro')?>">Livro</a></li>
                        		<li><a href="<?php echo $this->basePath('material/dicionario')?>">Dicionário</a></li>
                        	</ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Jonathan Ralph <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
